backend:
  name: github
  repo: manuel-rhdt/manuel-reinhardt.de # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "apps" # Used in routes, e.g., /admin/collections/blog
    label: "Apps" # Used in the UI
    folder: "content/app" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Appstore Link", name: "applink", widget: "string"}
      - {label: "Screenshots", name: "screenshots", widget: "markdown"}